export interface ApplicationModel {
        firstName: string,
        lastName: string,
        fullName:string,
        phoneNumber:string,
        idNumber:string,
        maritalStatus:string,
        spouseName:string,
        spouseIdNumber:string,
        village:string,
        location:string,
        county:string,
        subCounty:string,
        businessName:string,
        businessLocation:string,
        nextOfKin:string,
        nextOfKinPhone:string,
        loanAmount:number,
        loanTerm:number,
        paymentFrequency:string,
        collateralType:string,
        collateralValue:number,
        collateralFile:string
};
